networks:
    blazorsqlserverdev-network:
        driver: bridge

volumes:
  sqlserverdata:

services:
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev-db
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
        - sqlserverdata:/var/opt/mssql
    networks:
      - blazorsqlserverdev-network

  blazorsqlserverdev:
    image: ${DOCKER_REGISTRY-}blazorsqlserverapp
    container_name: blazor-sqlserver-app
    ports:
        - 8081:8080
    build:
      context: BlazorSqlServerDev
      dockerfile: Dockerfile
    networks:
        - blazorsqlserverdev-network
    depends_on:
      - sqlserverdb
